config/routes.rb
Musicapp::Application.routes.draw do
  resource :session, only: [:create, :destroy, :new]
  resources :users, only: [:create, :new, :show] do
    get :activate, on: :collection
  end

  shallow do
    resources :bands do
      resources :albums do
        resources :tracks
      end
    end
  end

  ###
  # Note that,
  ###
  # shallow do
  #   resources :albums do
  #     resources :tracks
  #   end
  # end
  ###
  # is the same as:
  ###
  # resources :albums do
  #   resources :tracks, only: [:new, :create, :index]
  # end
  # resources :tracks, only: [:show, :edit, :update, :destroy]
  ###
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :band
  has_many :tracks

  # can't use presence validation with boolean field
  validates :band, :name, :year, :presence => true
  validates :live, :inclusion => { :in => [true, false] }
  validates :name, :uniqueness => { :scope => :band_id }
  validates :year, :numericality => { :minimum => 1900, :maximum => 9000 }
end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :albums

  validates :name, :uniqueness => :true
  validates :name, :presence => :true
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album
  has_one :band, :through => :album, :source => :band

  validates :album, :lyrics, :name, :ord, :presence => true
  # can't use presence validation with boolean field
  validates :bonus, :inclusion => { :in => [true, false] }
  validates :ord, :uniqueness => { :scope => :album_id }
end

app/models/user.rb
class User < ActiveRecord::Base
  before_validation { |user| user.reset_session_token!(false) }

  validates(:password_digest,
            :session_token,
            :email,
            :presence => true
            )

  before_create :set_activation_token

#  validates(:email, :uniqueness => true)


# ActiveRecord::Base::generate_unique_token_for_field defined in lib/active_record_extension.rb
  def self.generate_session_token
    self.generate_unique_token_for_field(:session_token)
  end

  def self.find_by_credentials(email, secret)
    user = User.find_by_email(email)

    user.is_password?(secret) ? user : nil
  end

  def set_activation_token
    self.activation_token = self.class.generate_unique_token_for_field(:activation_token)
  end

  def password=(secret)
    @password = secret
    self.password_digest = BCrypt::Password.create(secret).to_s
  end

  def is_password?(secret)
    BCrypt::Password.new(self.password_digest).is_password?(secret)
  end

  def reset_session_token!(force = true)
    return unless self.session_token.nil? || force

    self.session_token = User.generate_session_token
    self.save!
  end

  def activate!
    self.update_attribute(:activated, true)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      render :new
    end
  end

  def index
    @albums = Album.all
  end

  def new
    @album = Album.new(:band_id => params[:band_id])
  end

  def show
    @album = Album.find(params[:id])
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    if @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      render :edit
    end
  end

  private
  def album_params
    params.require(:album).permit(:band_id, :live, :name, :year)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
  end

  def show
    @band = Band.find(params[:id])
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      render :new
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    @band.update_attributes(band_params)

    redirect_to band_url(@band)
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if user.nil?
      flash.now[:errors] ||= []
      flash.now << "Login failed. Check yo' self."
      render :new

    # Notice we have User#activated? even though we didn't define it!
    # Rails gives you this method for free because it matches a column name.
    elsif !user.activated?
      redirect_to root_url, alert: "You must activate your account first! Check your email."
    else
      login_user!(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil

    redirect_to new_session_url
  end

  def new
    render :new
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      render :new
    end
  end

  def index
    @tracks = Track.all
  end

  def new
    @track = Track.new(:album_id => params[:album_id])
  end

  def show
    @track = Track.find(params[:id])
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
  end

  def edit
    @track = Track.find(params[:id])
  end

  def update
    @track = Track.find(params[:id])
    @track.update_attributes(track_params)

    redirect_to track_url(@track)
  end

  private
  def track_params
    params.require(:track).permit(:album_id, :bonus, :lyrics, :name, :ord)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.activation_email(@user).deliver!
      redirect_to root_url, notice: "Successfully created your account! Check your inbox for an activation email."
    else
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def show
    @user = User.find(params[:id])
  end

  def activate
    @user = User.find_by_activation_token(params[:activation_token])

    # Check for presence of activation token in params to prevent
    # fetching a user from the db that has a nil activation_token
    # for some reason.
    if params[:activation_token] && @user
      @user.activate!
      login_user! @user
      redirect_to @user, notice: "Successfully activated your account!"
    else
      raise ActiveRecord::RecordNotFound.new()
    end
  end


  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def current_user_id
    current_user ? current_user.id : nil
  end

  def login_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def require_user!
    redirect_to sessions_url if current_user.nil?
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<h1>Albums</h1>

<ul>
  <% @albums.each do |album| %>
    <li><%= album_link(album) %></li>
  <% end %>
</ul>

<%= link_to "New album", new_album_url %>

app/views/albums/new.html.erb
<form action="<%= band_albums_url(@album.band_id) %>" method="post">
    <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
    >

    <label for="album_name">Name</label>
    <input
    type="text"
    name="album[name]"
    id="album_name"
    value="<%= @album.name %>"
    >
    <br>


    <label for="album_band">Band</label>
    <select name="album[band_id]" id="album_band">
        <% Band.all.each do |band| %>
            <option
                <%= @album.band_id == band.id ? "selected" : "" %>
                value="<%= band.id %>"
            >
                <%= band.name.upcase %>
            </option>
        <% end %>
    </select>
    <br>

    <input
    type="radio"
    name="album[live]"
    value="t"
    id="album_live_t"
    <%= @album.live ? "checked" : "" %>
    >
    <label for="album_live_t">Live</label>

    <input
    type="radio"
    name="album[live]"
    value="f"
    id="album_live_f"
    <%= @album.live ? "" : "checked" %>
    >
    <label for="album_live_f">Studio</label>
    <br>

    <label for="band_year">Year</label>
    <input
    type="number"
    name="album[year]"
    id="album_year"
    value="<%= @album.year %>">
    <br>


    <input type="submit" value="Create Album!">
</form>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>

<ul>
  <% @album.tracks.each do |track| %>
    <li><%= link_to track.name, track_url(track) %></li>
  <% end %>
</ul>

<h4>Links</h4>
<ul>
  <li><%= link_to "New track", new_album_track_url(@album) %></li>
  <li><%= link_to @album.band.name, band_url(@album.band) %></li>
</ul>

app/views/bands/index.html.erb
<h1>Bands</h1>

<ul>
  <% @bands.each do |band| %>
    <li><%= link_to band.name, band %></li>
  <% end %>
</ul>

<%= link_to "New band", new_band_url %>

app/views/bands/new.html.erb
<%= form_for(@band) do |f| %>
  <%= f.text_field :name %>
  <br>
  
  <%= f.submit %>
<% end %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<ul>
  <% @band.albums.each do |album| %>
    <li><%= link_to album.name, album_url(album) %></li>
  <% end %>
</ul>

<h4>Links</h4>
<ul>
  <li><%= link_to "New album", new_band_album_url(@band) %></li>
  <li><%= link_to "All bands", bands_url %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Musicapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tracks/index.html.erb
<h1>Tracks</h1>

<ul>
  <% @tracks.each do |track| %>
    <li><%= track_link(track) %></li>
  <% end %>
</ul>

app/views/tracks/new.html.erb
<%= form_for([@track.album, @track]) do |f| %>
  <%= f.text_field :name %>
  <br>

  <%= f.collection_select :album_id, Album.all, :id, :name %>
  <br>

  <%= f.number_field :ord %>
  <br>

  <%= f.radio_button :bonus, "false" %>
  <%= f.label :bonus, "Standard", :value => "false" %>
  <br>
  <%= f.radio_button :bonus, "true" %>
  <%= f.label :bonus, "Bonus", :value => "true" %>
  <br>

  <%= f.label :lyrics %>
  <%= f.text_area :lyrics %>
  <br>

  <%= f.submit %>
<% end %>

app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>

<%= link_to @track.album.name, album_url(@track.album) %>

app/views/users/new.html.erb
<h1>New User</h1>

<form action="<%= users_url %>" method="post">
    <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>"
    >

    <label for="user_email">Email</label>
    <input type="text" name="user[email]" id="user_email">
    <br>

    <label for="user_password">Password</label>
    <input type="password" name="user[password]" id="user_password">
    <br>

    <input type="submit">
</form>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>
<p><%= button_to "Logout", session_url, method: :delete %></p>